'use client';
import { useMemo, useState } from 'react';
import { allWords, getQuizHistory, saveQuizHistory, updateReview } from '@/lib/store';

type Mode='en2cn'|'cn2en';
export default function Quiz(){const [mode,setMode]=useState<Mode>('en2cn');const [index,setIndex]=useState(0);const [score,setScore]=useState(0);const [picked,setPicked]=useState<string|undefined>();const qs=useMemo(()=>allWords.slice(0,20).map(w=>{const pool=allWords.filter(v=>v.id!==w.id).sort(()=>Math.random()-0.5).slice(0,3);const options=[w,...pool].sort(()=>Math.random()-0.5);return{w,options};}),[]);const q=qs[index]; if(!q) return <div>完成，得分 {score}/{qs.length}</div>;
const submit=(id:string)=>{if(picked)return;setPicked(id);const ok=id===q.w.id; if(ok){setScore(s=>s+1); updateReview(q.w.id,'know')} else updateReview(q.w.id,'dont'); if(index===qs.length-1){const h=getQuizHistory();h.unshift({id:Date.now().toString(),createdAt:new Date().toISOString(),book:'mixed',total:qs.length,correct: ok?score+1:score,wrong: ok?qs.length-score-1:qs.length-score,score:Math.round(((ok?score+1:score)/qs.length)*100)});saveQuizHistory(h.slice(0,20));}
setTimeout(()=>{setIndex(v=>v+1);setPicked(undefined)},500)};
return <div><h1 className='text-xl font-bold mb-3'>测验模式</h1><div className='flex gap-2 mb-3'><button onClick={()=>setMode('en2cn')} className='border rounded px-2 py-1'>英译中</button><button onClick={()=>setMode('cn2en')} className='border rounded px-2 py-1'>中译英</button></div><p className='mb-3'>第 {index+1}/{qs.length} 题</p><p className='font-semibold mb-3 text-lg'>{mode==='en2cn'?q.w.word:q.w.meaningCn}</p><div className='space-y-2'>{q.options.map(o=>{const label=mode==='en2cn'?o.meaningCn:o.word; const cls=picked? (o.id===q.w.id?'bg-green-100':o.id===picked?'bg-rose-100':'bg-white'):'bg-white'; return <button key={o.id} onClick={()=>submit(o.id)} className={`block w-full border rounded p-2 text-left ${cls}`}>{label}</button>})}</div><p className='mt-4'>得分：{score}</p></div>}
